"""add_kms_agent_keys_table

Revision ID: 0fa63545292d
Revises: b7c1e2f3a4d5
Create Date: 2026-05-02 16:05:48.282181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa63545292d'
down_revision: Union[str, Sequence[str], None] = 'b7c1e2f3a4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kms_agent_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('privkey_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kms_agent_keys')
    # ### end Alembic commands ###
