"""initial schema

Revision ID: 5ef3a914c6e6
Revises: 
Create Date: 2026-04-27 21:02:20.247698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5ef3a914c6e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector extension must exist before any VECTOR column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mandate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_agent_time', 'audit_log', ['agent_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index('ix_audit_user_time', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nullifier_hash', sa.Text(), nullable=False),
    sa.Column('attributes_proven', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes_verified_at', sa.DateTime(), nullable=False),
    sa.Column('attributes_expires_at', sa.DateTime(), nullable=False),
    sa.Column('passkey_credential_id', sa.Text(), nullable=False),
    sa.Column('passkey_pubkey', sa.Text(), nullable=False),
    sa.Column('passkey_sign_count', sa.Integer(), nullable=True),
    sa.Column('notification_email', sa.Text(), nullable=True),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_nullifier_hash'), 'users', ['nullifier_hash'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('pubkey', sa.Text(), nullable=False),
    sa.Column('privkey_kms_ref', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('reservation_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('ideal_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('hard_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soft_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intents_active_category_side', 'intents', ['status', 'category', 'side'], unique=False)
    op.create_table('mandates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('step_up_required_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spent_total_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deals_count', sa.Integer(), nullable=True),
    sa.Column('spent_today_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_reset_date', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('signature', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canonical_payload', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('buy_intent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sell_intent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('price_overlap', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buy_intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['sell_intent_id'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buy_intent_id', 'sell_intent_id', name='uq_match')
    )
    op.create_table('negotiations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('match_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rounds_used', sa.Integer(), nullable=True),
    sa.Column('max_rounds', sa.Integer(), nullable=True),
    sa.Column('current_price_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('negotiation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('buyer_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('seller_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('buy_intent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sell_intent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('final_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('buyer_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('buyer_signed_at', sa.DateTime(), nullable=True),
    sa.Column('seller_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seller_signed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['buy_intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.ForeignKeyConstraint(['sell_intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('deal_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('deal_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_messages')
    op.drop_table('deals')
    op.drop_table('negotiations')
    op.drop_table('matches')
    op.drop_table('mandates')
    op.drop_index('ix_intents_active_category_side', table_name='intents')
    op.drop_table('intents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_nullifier_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_audit_user_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index('ix_audit_agent_time', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
